
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author b0-0sk
 */
public class LoginForm extends JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel(); // Tablero 1 donde estara el la "X" "-" y el "Login Form"
        jLabelClose = new JLabel(); // Etiqueta donde se cerrara la aplicacion "X"
        jLabel2 = new JLabel(); // Etiqueta donde estara el Texto de "Login Form"
        jLabelMin = new JLabel();// Recuadro con la funcion de Minimizar "-"
        
        jPanel2 = new JPanel(); // Tablero 2
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jTextField1 = new JTextField();
        jPasswordField1 = new JPasswordField();
        jButton1 = new JButton(); // Cancel
        jButton2 = new JButton(); // Login 
        jLabelRegister = new JLabel(); // Etiqueta de registro

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE); // Salir de la aplicación utilizando el método de salida del sistema
        setUndecorated(false); // Poner barra para minimazr maximizar y cerrar
        
        /** Tablero 1 **/

        jPanel1.setBackground(new Color(248, 148, 6)); // Color del fondo
        
        /** Etiqueta X **/

        jLabelClose.setFont(new Font("Tahoma", 1, 24)); // Fuente del titulo
        jLabelClose.setForeground(new Color(255, 255, 255)); // Color del titulo
        jLabelClose.setText("X"); // X para cerrar
        jLabelClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new MouseAdapter() { // Listener del mouse para que si cierra que responda
            public void mouseClicked(MouseEvent evt) { // Cuando el mouse haga un click se crea un evento
                jLabelCloseMouseClicked(evt); // Ejecuta el evento cerrar
            }
        });

        /** Etiqueta Login Form **/

        jLabel2.setFont(new Font("Tahoma", 1, 24)); 
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("Login Form");
        
        /** Etiqueta - **/
        
        jLabelMin.setFont(new Font("Tahoma", 1, 24)); // 
        jLabelMin.setForeground(new Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Cambiar el sprite del raton
        jLabelMin.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabelMinMouseClicked(evt); // Ejecuta el evento minimizar
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1); //Variable para definir el diseño "Horizontal" o "Vertical"
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup( // Assignar el grupo horizontal
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING) //Assignar de que es el grupo principal
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup() // Alfinal añadir la sequencia del grupo "jPanel1Layout"
               
            	.addGap(20)
            	.addComponent(jLabel2)
                .addGap(180) 
                .addComponent(jLabelMin) // añadir componente "-"
                .addGap(25) // Espacio añadidos
                .addComponent(jLabelClose)// añadir componente "X"
                .addGap(18, 18, 18)
                //.addGap(29, 29, 29)
                //.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            	//.addContainerGap(236, Short.MAX_VALUE)

                
             )
           /* .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2)
                    .addContainerGap(236, Short.MAX_VALUE)))
            */
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabelClose))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new Color(44, 62, 80));

        jLabel4.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new Color(236, 240, 241));
        jLabel4.setText("Username:");

        jLabel5.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new Color(236, 240, 241));
        jLabel5.setText("Password:");

        jTextField1.setBackground(new Color(108, 122, 137));
        jTextField1.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setForeground(new Color(228, 241, 254));

        jPasswordField1.setBackground(new Color(108, 122, 137));
        jPasswordField1.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new Color(228, 241, 254));

        jButton1.setBackground(new Color(34, 167, 240));
        jButton1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("Login");

        jButton2.setBackground(new Color(242, 38, 19));
        jButton2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setText("Cancel");

        jLabelRegister.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jLabelRegister.setForeground(new Color(255, 255, 255));
        jLabelRegister.setText("click here to create a new account");
        jLabelRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabelRegister)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRegister)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
       
        System.exit(0);
        
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        
        this.setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelRegisterMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabelClose;
    private JLabel jLabelMin;
    private JLabel jLabelRegister;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPasswordField jPasswordField1;
    private JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
